# Generated by Django 5.2.4 on 2025-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_provider', '0002_passwordlessauthmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_pla_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordlessauthmodel',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
